
package gr.wind.spectra.consumer.oneway;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "InterfaceWebSpectra", targetNamespace = "http://web.spectra.wind.gr/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface InterfaceWebSpectra
{

	/**
	 * 
	 * @param password
	 * @param userName
	 * @param parameters
	 */
	@WebMethod
	@Oneway
	@Action(input = "http://web.spectra.wind.gr/InterfaceWebSpectra/submitOutage")
	public void submitOutage(
			@WebParam(name = "submitOutage", targetNamespace = "http://web.spectra.wind.gr/", partName = "parameters") SubmitOutage parameters,
			@WebParam(name = "UserName", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "UserName") String userName,
			@WebParam(name = "Password", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "Password") String password);

	/**
	 * 
	 * @param password
	 * @param userName
	 * @param parameters
	 */
	@WebMethod
	@Oneway
	@Action(input = "http://web.spectra.wind.gr/InterfaceWebSpectra/getOutageStatus")
	public void getOutageStatus(
			@WebParam(name = "getOutageStatus", targetNamespace = "http://web.spectra.wind.gr/", partName = "parameters") GetOutageStatus parameters,
			@WebParam(name = "UserName", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "UserName") String userName,
			@WebParam(name = "Password", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "Password") String password);

	/**
	 * 
	 * @param password
	 * @param userName
	 * @param parameters
	 */
	@WebMethod
	@Oneway
	@Action(input = "http://web.spectra.wind.gr/InterfaceWebSpectra/modifyOutage")
	public void modifyOutage(
			@WebParam(name = "modifyOutage", targetNamespace = "http://web.spectra.wind.gr/", partName = "parameters") ModifyOutage parameters,
			@WebParam(name = "UserName", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "UserName") String userName,
			@WebParam(name = "Password", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "Password") String password);

	/**
	 * 
	 * @param password
	 * @param userName
	 * @param parameters
	 */
	@WebMethod
	@Oneway
	@Action(input = "http://web.spectra.wind.gr/InterfaceWebSpectra/closeOutage")
	public void closeOutage(
			@WebParam(name = "closeOutage", targetNamespace = "http://web.spectra.wind.gr/", partName = "parameters") CloseOutage parameters,
			@WebParam(name = "UserName", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "UserName") String userName,
			@WebParam(name = "Password", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "Password") String password);

	/**
	 * 
	 * @param password
	 * @param userName
	 * @param parameters
	 */
	@WebMethod(operationName = "NLU_Active")
	@Oneway
	@Action(input = "http://web.spectra.wind.gr/InterfaceWebSpectra/NLU_Active")
	public void nluActive(
			@WebParam(name = "NLU_Active", targetNamespace = "http://web.spectra.wind.gr/", partName = "parameters") NLUActive parameters,
			@WebParam(name = "UserName", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "UserName") String userName,
			@WebParam(name = "Password", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "Password") String password);

	/**
	 * 
	 * @param password
	 * @param userName
	 * @param parameters
	 */
	@WebMethod
	@Oneway
	@Action(input = "http://web.spectra.wind.gr/InterfaceWebSpectra/getHierarchy")
	public void getHierarchy(
			@WebParam(name = "getHierarchy", targetNamespace = "http://web.spectra.wind.gr/", partName = "parameters") GetHierarchy parameters,
			@WebParam(name = "UserName", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "UserName") String userName,
			@WebParam(name = "Password", targetNamespace = "http://web.spectra.wind.gr/", header = true, partName = "Password") String password);

}
